{
    "info":
        {
        "statuscode":0,
        "copyright":
            {
            "text": "\u00A9 2020 MapQuest, Inc.",
            "imageUrl":"http://api.mqcdn.com/res/mqlogo.gif",
            "imageAltText":"\u00A9 2020 MapQuest, Inc."
            },
            "messages":[]
        },
    "options":
        {
        "maxResults":-1,
        "thumbMaps":true,
        "ignoreLatLngInput":false
        },
    "results":[
        {
        "providedLocation":
            {
            "location":"Dodgeville,WI"
            },
        "locations":[
            {
            "street":"",
            "adminArea6":"",
            "adminArea6Type":"Neighborhood",
            "adminArea5":"Dodgeville",
            "adminArea5Type":"City",
            "adminArea4":"Iowa County",
            "adminArea4Type":"County",
            "adminArea3":"WI",
            "adminArea3Type":"State",
            "adminArea1":"US",
            "adminArea1Type":"Country",
            "postalCode":"",
            "geocodeQualityCode":"A5XAX",
            "geocodeQuality":"CITY",
            "dragPoint":false,
            "sideOfStreet":"N",
            "linkId":"282034258",
            "unknownInput":"",
            "type":"s",
            "latLng":
                {
                "lat":42.963772,
                "lng":-90.128563
                },
            "displayLatLng":
                {
                "lat":42.963772,
                "lng":-90.128563
                },
            "mapUrl":"http://www.mapquestapi.com/staticmap/v5/map?key=oiX815Jb2u30RoL5uKEc8khC8tFZB6jE&type=map&size=225,160&locations=42.963772,-90.128563|marker-sm-50318A-1&scalebar=true&zoom=12&rand=-763974958"
            }]
        }
    ]
}